### ISSUE TITLE
Error at "Installing native libraries for Couchbase Lite for android"

### ISSUE THREAD

**Issue by alfiepoleon** [cbl-dart/cbl-dart#258]
**Describe the bug**

When building the app it gets to `Installing native libraries for Couchbase Lite for android` then exits fatally.
Log inserted below.

**To Reproduce**

Was working fine, upgraded to null-safety, ran `flutter clean` then `flutter pub get`. Works fine till that point
Then this happens when I run the app from VS Code run.

```bash
Launching lib/main.dart on Android SDK built for x86 in debug mode...
lib/main.dart:1
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Installing native libraries for Couchbase Lite for android
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':cbl_flutter_ce:installLibraries'.
> Process 'command './tool/install_libraries.sh'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
Error in line 146 in file ./tool/install_libraries.sh

BUILD FAILED in 15s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
```

**Expected behavior**
That it builds and runs

**Screenshots**
![image](https://user-images.githubusercontent.com/14350051/144125981-3d02a101-3fea-4d15-9f35-070394a922f8.png)

**Environment (please complete the following information):**

 - OS: Ubuntu 21.10
 - `cbl`: ^1.0.0-beta.11
 - `cbl_flutter`: ^1.0.0-beta.10
 - `cbl_flutter_ce`:  ^1.0.0-beta.4

**Additional context**

**Comment by blaugold** [comment]
Hey @alfiepoleon,
thanks for filing this bug. This is a known issue which is being worked on in #257. 
Until this is fixed, please use the previous beta.
I'm planing to publish a new beta, with a fix, tomorrow.

**Comment by alfiepoleon** [comment]
@blaugold thank you for getting back to me, I have been downgrading progressively, I'm now at
```yaml
  cbl: ^1.0.0-beta.9
  cbl_flutter: ^1.0.0-beta.8
  cbl_flutter_ce: ^1.0.0-beta.2
```
Still doesn't work, same error as the latest, is there anything I might be missing? Doing a `flutter clean` at every downgrade

**Comment by blaugold** [comment]
If you're using the `^` range modifier in front of the versions, you're still getting the latest versions. To pin a dependency to an exact version, you will need to use the version without any range modifier.

**Comment by alfiepoleon** [comment]
@blaugold aah rookie mistake, thanks for that, it works now with this config
```yaml
  cbl: 1.0.0-beta.10
  cbl_flutter: 1.0.0-beta.9
  cbl_flutter_ce: 1.0.0-beta.3
```

**Comment by PlutoHDDev** [comment]
I'm currently trying to implement the packages in a completely new app, so I have the latest version of everything. When I run the app, I get a similar error. What can I do about this?
```
flutter run
Launching lib\main.dart on Pixel 6 Pro in debug mode...
Der Befehl "C:/Program" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':cbl_flutter_ce:installLibraries'.
> Process 'command 'cmd'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
Running Gradle task 'assembleDebug'...                             14,6s
Exception: Gradle task assembleDebug failed with exit code 1
```

**Comment by blaugold** [comment]
@PlutoHDDev Thanks for reporting this issue. I believe this is a different bug and have created #338 to track it.
