### ISSUE TITLE
Connection resets when syncing with encryption

### ISSUE THREAD

**Issue by nblum37** [cbl-dart/cbl-dart#291]
Hi,

since our upgrade from 0.6.x to 1.0.0-beta[x], we face some connection issues with the replicator when syncing blobs. As soon as the document with the blob should be pulled by the replicator, a `DatabaseException(errno 104: Connection reset by peer, code: unexpectedError)` is thrown leading the replicator to go offline. The blob document is never replicated during the retries. Everything works fine with cbl 0.6.0.

I guess, it might be hard to reproduce the error, as the problem will probably depend on the whole system. But maybe you can give us some advice on how to continue debugging. I'm also not sure whether it's a package problem or a cbl core issue. Thank you.

1. Save a blob to cbl like 
<img width="422" alt="Bildschirmfoto 2022-02-08 um 03 27 01" src="https://user-images.githubusercontent.com/82163574/152907527-b2a2df9d-4a50-485e-ae78-708f53ff5cc6.png">

2. Wait until the document was pushed to the sync gateway

3. Delete the local cbl database 

4. Create a local cbl database and resync via replicator with the backend

5. All documents are pulled, except the blob document 
<img width="1306" alt="Bildschirmfoto 2022-02-08 um 03 04 58" src="https://user-images.githubusercontent.com/82163574/152907724-c0632a1f-fc4e-4c6d-a5b6-3987817f2eb8.png">

6. The sync gateway does not show any error only the closed connection
<img width="1189" alt="Bildschirmfoto 2022-02-08 um 03 04 18" src="https://user-images.githubusercontent.com/82163574/152908023-122fa69e-c863-4096-9a91-33350de92cef.png">

 - OS: Android
 - `cbl`: 1.0.0-beta14
 - `cbl_flutter`: 1.0.0-beta12
 - `cbl_flutter_ce`: 1.0.0-beta5

- Backend: Docker Sync Gateway 2.8.2
- Reverse proxy: HaProxy

**Comment by blaugold** [comment]
Hi @nblum37,
Thanks for the detailed report.
I'm going to try to replicate the issue.

In the meantime, could you try whether the issue persists with Sync Gateway 2.8.3 and 3.0.0-beta2?

**Comment by blaugold** [comment]
I tried replication this with Sync Gateway 2.8.2, 2.8.3 and 3.0.0-beta2, but was unable to yet.
I didn't use a reverse proxy to verify that the basic functionality works.

Comparing the Sync Gateway logs from a successful PULL replication (with Blob), it seems to me that in your case there is some kind of networking issue. 
```
2022-02-08T08:33:12.414Z [INF] HTTP:  #074: GET /db/_blipsync (as GUEST)
2022-02-08T08:33:12.414Z [INF] HTTP: #074:     --> 401 Login required  (0.6 ms)
2022-02-08T08:33:12.434Z [INF] HTTP:  #075: GET /db/_blipsync (as Jane)
2022-02-08T08:33:12.435Z [INF] HTTP+: #075:     --> 101 [20d8c5e1] Upgraded to BLIP+WebSocket protocol (as Jane)  (0.0 ms)
2022-02-08T08:33:12.435Z [INF] WS: c:#075 Start BLIP/Websocket handler
2022-02-08T08:33:12.441Z [INF] SyncMsg: c:[20d8c5e1] #1: Type:getCheckpoint Client:cp-tKXTmuKg7lWs4pPY71c/VLyig5I=
2022-02-08T08:33:12.441Z [INF] SyncMsg: c:[20d8c5e1] #1: Type:getCheckpoint   --> 404 missing Time:232µs
2022-02-08T08:33:12.443Z [INF] SyncMsg: c:[20d8c5e1] #2: Type:subChanges Since:0 ActiveOnly:true 
2022-02-08T08:33:12.444Z [INF] Sync: c:[20d8c5e1] Sending changes since 0
2022-02-08T08:33:12.445Z [INF] SyncMsg: c:[20d8c5e1] #3: Type:proposeChanges #Changes: 0
2022-02-08T08:33:12.445Z [INF] Changes: c:[20d8c5e1] MultiChangesFeed(channels: {*}, options: {Since: 0, Limit: 0, Conflicts: false, IncludeDocs: false, Wait: false, Continuous: false, HeartbeatMs: 0, TimeoutMs: 0, ActiveOnly: true}) ...   (to Jane)
2022-02-08T08:33:12.446Z [INF] Cache: c:[20d8c5e1] GetCachedChanges("*", 0) --> 1 changes valid from #1
2022-02-08T08:33:12.446Z [INF] Changes: c:[20d8c5e1] MultiChangesFeed done   (to Jane)
2022-02-08T08:33:12.450Z [INF] Sync: c:[20d8c5e1] Sent 1 changes to client, from seq 3
2022-02-08T08:33:12.450Z [INF] Sync: c:[20d8c5e1] Sent all changes to client
2022-02-08T08:33:12.459Z [INF] SyncMsg: c:[20d8c5e1] #4: Type:getAttachment Digest:sha1-cDeAcZjCKn0rCAc3HXY3eahP388= 
2022-02-08T08:33:12.492Z [INF] SyncMsg: c:[20d8c5e1] #5: Type:setCheckpoint Client:cp-tKXTmuKg7lWs4pPY71c/VLyig5I= 
2022-02-08T08:33:12.714Z [INF] HTTP: c:[20d8c5e1] #075:    --> BLIP+WebSocket connection closed
```

I'm not seeing this line in your Sync Gateway logs:
```
2022-02-08T08:33:12.450Z [INF] Sync: c:[20d8c5e1] Sent all changes to client
```

And this line, in which the client sets a new checkpoint when it has received all changes:
```
2022-02-08T08:33:12.492Z [INF] SyncMsg: c:[20d8c5e1] #5: Type:setCheckpoint Client:cp-tKXTmuKg7lWs4pPY71c/VLyig5I= 
```

**Comment by blaugold** [comment]
It would be good to see detailed logs (`LogLevel.verbose`) from Couchbase Lite when this error happens.

**Comment by nblum37** [comment]
Pls find attached the verbose logging. The documents with blobs are
- 10a0b96c-4fd7-4bc6-967e-99e14e64f104
- 6ec2a57a-5b11-41c5-bb2e-0c4578a4750e

as changing the sync gateway version in our setup is not too easy, I will first try to tunnel around the reverse proxy to exclude a possible issue there.
<img width="1305" alt="Bildschirmfoto 2022-02-08 um 13 24 45" src="https://user-images.githubusercontent.com/82163574/152986850-ddc86ef7-f8d4-4d49-8b2d-eb3413de160c.png">

**Comment by nblum37** [comment]
And thank you very much for the support!

**Comment by nblum37** [comment]
Ok, I was able to connect the replicator directly to the sync gateway without the reverse proxy and it seems to work. We already had issues with the reverse proxy in the past, as the websocket timeout did not fit to the replicator default setting in the previous 0.x.x versions. Do you have any idea, what could have changed in the new cbl core version with the websocket connection properties? I will further investigate the reverse proxy settings and keep you posted.

**Comment by blaugold** [comment]
Not really. You can configure the web socket [heartbeat](https://pub.dev/documentation/cbl/1.0.0-beta.14/cbl/ReplicatorConfiguration/heartbeat.html) interval, which is 300s per default, but I doubt that should be a problem. 
It looks like the connection is rested in the middle of replication, so any applicable timeouts would have to be very short, right?

**Comment by nblum37** [comment]
Yes, I agree.
Yes, and all timeouts at the proxy side are much higher. Even the reverse proxy shows in the log termination code CD, saying that the TCP data session was unexpectedly aborted by the client.

**Comment by nblum37** [comment]
I created a topic at the Couchbase form now. Maybe someone has an idea. I assume 0.6 used cbl for C 2.8 and 1.0 uses cbl for C 3.0beta2?

**Comment by blaugold** [comment]
The CBL C SDK did not exist when CBL 2.8 was released and was pre beta and not versioned when CBL Dart 0.6 was published, so I only have the [commit](https://github.com/couchbase/couchbase-lite-C/compare/238cd7688f90d557b8d69e49a67dd4fb126e71f3). The current beta releases of CBL Dart use the [3.0.0-beta2](https://github.com/couchbase/couchbase-lite-C/commits/3.0.0-beta2) version of the CBL C SDK.

**Comment by nblum37** [comment]
Ahh ok, I see.

At the moment, it seems to be more an issue of the SSL connection and less about the proxy itself. Everything works fine over the proxy without SSL encryption. However, when turning on the SSL off-loading at the reverse proxy, the connection become instable (not only when syncing blobs - but blobs can't be transferred at all). And looking into Wireshark, it is CBL what first asks to close the SSL (encryption alert message) and then TCP connection.

**Comment by nblum37** [comment]
https://forums.couchbase.com/t/unable-to-pull-blobs-with-cbl3-0-and-reverse-proxy/32822/4

**Comment by blaugold** [comment]
Thanks for the update. Like mentioned in the forum thread, it would be interesting to know if SSL connections work without a proxy. 

I should add a test for that.

**Comment by nblum37** [comment]
It does even not work without proxy.

**Comment by blaugold** [comment]
I have been able to replicate this issue and described the necessary steps in the Couchbase Forum thread.

**Comment by nblum37** [comment]
Thank you for the effort!

**Comment by blaugold** [comment]
I'm closing this issue because the latest version is using the Couchbase Lite 3.0.0 GA version.

**Comment by nblum37** [comment]
Hi @blaugold,
it seems like the bug is solved completely including the more severe issue with the attachment syncing. Thank you again for your support during the debugging!

**Comment by blaugold** [comment]
That's great! Glad I could help.
