### ISSUE TITLE
Collection support

### ISSUE THREAD

**Issue by blaugold** [cbl-dart/cbl-dart#324]
Collections are a feature that already exists on [Couchbase Server](https://docs.couchbase.com/server/current/learn/data/scopes-and-collections.html). Couchbase Lite does not officially support it yet, but LiteCore does. Once Couchbase Lite C exposes it, we can implement it here.

See the [LiteCore docs](https://couchbase.github.io/couchbase-lite-core/C/html/group___collection.html#details) for details.

Initial feature request: https://github.com/cbl-dart/cbl-dart/issues/321#issuecomment-1063617412

**Comment by nblum37** [comment]
Is there any update from CB regarding this topic?

**Comment by blaugold** [comment]
Nothing official but the next feature release (containing collection support) is planned for the first half of this year and looking at the Couchbase Lite C repo most activity is around making things ready for a new release (small fixes and doc comment updates).

**Comment by nblum37** [comment]
Thanks for the update. Looking forward to it.
