### ISSUE TITLE
Exception while deleting a document with cbl 1.1.1

### ISSUE THREAD

**Issue by kolotum** [cbl-dart/cbl-dart#347]
**Describe the bug**

We are seeing some exceptions in our current app versions. 

When we connect the user we change the document and delete the previous document.
In some cases the id of the DocumentState is null in _deleteDocument of cbl_service.dart (cbl affected version: 1.1.1) and results in a null check error.

**Stacktrace**

> Channel.call.<fn> (channel.dart:155)
> ProxyDatabase.deleteDocument.<fn>.<fn>.<fn> (proxy_database.dart:208)
> DatabaseBase._runInTransaction.<fn>.<fn> (database_base.dart:220)
> BasicLock.synchronized (basic_lock.dart:33)
> CouchSyncedStorage._mergeDocument (couch_synced_storage.dart:152) 

**Error Message**

> SerializationError: No serializer registered for error: Null check operator used on a null value #0 CblService._deleteDocument (package:cbl/src/service/cbl_service.dart:418) #1 Channel.addStreamEndpoint.<anonymous closure> (package:cbl/src/service/channel.dart:211) #2 Channel._handleListenToStream.<anonymous closure> (package:cbl/src/service/channel.dart:359) #3 new Future.sync (dart:async/future.dart:296) #4 Channel._handleCallRequest (package:cbl/src/service/channel.dart:341) #5 Channel.open.<anonymous closure>.<anonymous closure> (package:cbl/src/service/channel.dart:266) #6 TracingDelegate.restoreTracingContext (package:cbl/src/tracing.dart:173) #7 _ServiceWorkerDelegate.initialize.<anonymous closure> (package:cbl/src/service/cbl_worker.dart:134) #8 Channel.open.<anonymous closure> (package:cbl/src/service/channel.dart:250) #9 _RootZone.runUnaryGuarded (dart:async/zone.dart:1618) #10 CastStreamSubscription._onData (dart:_internal/async_cast.dart:85) #11 _RootZone.runUnaryGuarded (dart:async/zone.dart:1618) #12 _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341) #13 _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271) #14 _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63) #15 _EventSinkWrapper.add (dart:async/stream_transformers.dart:13) #16 _ChunkConversionSinkTransformer.add (package:cbl/src/service/serialization/serialization_codec.dart:101) #17 _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72) #18 _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111) #19 _RootZone.runUnaryGuarded (dart:async/zone.dart:1618) #20 _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341) #21 _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271) #22 _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774) #23 _StreamController._add (dart:async/stream_<truncated: 1329 chars>

**Environment:**

- cbl: 1.1.1
- cbl_flutter: 1.0.0+2
- cbl_flutter_ee: 1.1.1

**Comment by blaugold** [comment]
Thanks for reporting this issue.

**Comment by blaugold** [comment]
I have published `cbl` 1.1.2 with a fix for this issue.
