### ISSUE TITLE
Search documents by ids

### ISSUE THREAD

**Issue by devon** [cbl-dart/cbl-dart#356]
**Describe the bug**

Try to search documents with `id IN array`:

```dart
SELECT META().id AS id, * as attrs from _ WHERE id IN ["123", "456"]
```

But get an error:

```shell
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: DatabaseException(N1QL syntax error near character 55, code: invalidQuery)
SELECT META().id AS id, * as attrs from _ WHERE id IN ["123", "456"]
                                                      ^

#0      Channel.call.<anonymous closure> (package:cbl/src/service/channel.dart:155:13)
<asynchronous suspension>
#1      ProxyQuery._performPrepare.<anonymous closure> (package:cbl/src/query/proxy_query.dart:143:23)
<asynchronous suspension>
#2      AsyncQuery.fromN1ql (package:cbl/src/query/query.dart:243:5)
<asynchronous suspension>
```

**To Reproduce**

1. Run a search query on any buckets with `id IN ["an_id"]`

**doc**

https://docs.couchbase.com/couchbase-lite/current/android/query-n1ql-mobile.html#lbl-ops-binary

https://stackoverflow.com/questions/57285808/in-operator-in-couchbase-lite

**Comment by blaugold** [comment]
You should be able to make this work by using `(...)` instead of `[...]`: 
```sql
SELECT META().id AS id, * as attrs from _ WHERE id IN ("123", "456")
```

I think there is an issue to support array syntax for `IN` but I can't find it right now.
