### ISSUE TITLE
Let's Encrypt handshake error on Android 6

### ISSUE THREAD

**Issue by filipenanclarez** [cbl-dart/cbl-dart#387]
**Describe the bug**

```
I/flutter ( 8191): 00:47:31.046247| [DB] error: mbedTLS(C): x509_verify_cert() returned -9984 (-0x2700)
I/flutter ( 8191): 00:47:31.048299| [DB] error: mbedTLS(C): SockPP: mbedtls error -0x2700 from mbedtls_ssl_handshake: X509 - Certificate verification failed, e.g. CRL, CA or signature check failed
I/flutter ( 8191): 00:47:31.050706| [DB] error: mbedTLS(C): SockPP: ---closing mbedtls_socket with error (mbed status -0x2700, last_error -9984) ---
I/flutter ( 8191): 00:47:31.209377| [WS] error: TCPSocket TLS handshake failed; cert verify status 0x01
I/flutter ( 8191): 00:47:31.214290| [WS] error: {N8litecore9websocket16BuiltInWebSocketE#2} WebSocket failed to connect! (reason=Network error 7)
I/flutter ( 8191): 00:47:31.217310| [Sync] error: {Repl#1} Got LiteCore error: Network error 7, "The certificate validity has expired"
```

**To Reproduce**

Using replicator with gateway hosted in a server with Let's Encrypt TLS configuration, and try to make a sync in a device with Android 6
With other devices (Windows, Android 9+, iOS) this problem never happend.

**Expected behavior**

The replicator cannot recognize the trust of intermediate chains like explain in this thread:

https://stackoverflow.com/questions/69511057/flutter-on-android-7-certificate-verify-failed-with-letsencrypt-ssl-cert-after-s

I try to use use the solution posted in this post https://stackoverflow.com/a/71090239/5956942 but couchlite core not reconize the Security Context Certificate.

Can you make couchlite works with `SecurityContext.defaultContext` or provide some another solution for this problem with Let's Encripty?

**Environment (please complete the following information):**

 - OS: Android 6
 - `cbl`: ^1.2.0
 - `cbl_flutter`: ^1.0.0+3
 - `cbl_flutter_ce`: ^1.1.1

PS.: I tried to use a self signed cert like doc sugest in https://docs.couchbase.com/sync-gateway/current/authentication-certs.html#creating-a-self-signed-certificate but still not works

**Comment by blaugold** [comment]
Thanks for reporting this. 

As a workaround, you can set [`pinnedServerCertificate`](https://pub.dev/documentation/cbl/latest/cbl/ReplicatorConfiguration/pinnedServerCertificate.html) to the certificate issued by Let's Encrypt for your server, when creating your `ReplicatorConfiguration`.

I'm going to provide a way to set your own root certificates when creating your `ReplicatorConfiguration`, so you can configure the Let's Encrypt root certificate.

**Comment by filipenanclarez** [comment]
> Thanks for reporting this.
> 
> As a workaround, you can set [`pinnedServerCertificate`](https://pub.dev/documentation/cbl/latest/cbl/ReplicatorConfiguration/pinnedServerCertificate.html) to the certificate issued by Let's Encrypt for your server, when creating your `ReplicatorConfiguration`.
> 
> I'm going to provide a way to set your own root certificates when creating your `ReplicatorConfiguration`, so you can configure the Let's Encrypt root certificate.

Can you give some price of code with this workaroud? 

Can i use self signed cert with this workaround?

**Comment by blaugold** [comment]
```dart
import 'dart:convert';

// The cert in PEM
const cert = '''
...
''';

ReplicatorConfiguration(pinnedServerCertificate: Uint8List.fromList(utf8.encode(cert)));
```

A self-signed cert should work too.

**Comment by blaugold** [comment]
Using Let's Encrypt certificates should work normally in the 2.1.0 release of `cbl_dart`, `cbl_flutter_ce` and `cbl_flutter_ee`. Please comment if the issue persists.

**Comment by filipenanclarez** [comment]
Hi, 

Thank you for workaround, and for the fix on cbl 2.1.0

But i still have some problems.

Your version of cbl 2.1.0 update dependences (specially ffi) and force the anroid minimum sdk to 33. This put all my clients with android 6 out of game.

About your workaround, the problem is the let's encrypt renew certificates after 3 months. So every time the certificates renews, i need build another version of app.

Let me know if you have better solution for this.

Regards.

**Comment by blaugold** [comment]
> Your version of cbl 2.1.0 update dependences (specially ffi) and force the anroid minimum sdk to 33. This put all my clients with android 6 out of game.

I was not aware of those changes to the minimum SDK in dependencies. Couchbase Lite itself has a minimum of 22 and that is what I try to support, too. I'll look into lowering the dependency constraints where possible, but it would be helpful if you could point out the specific dependencies that require these minimum SDK versions.

> About your workaround, the problem is the let's encrypt renew certificates after 3 months. So every time the certificates renews, i need build another version of app.

I believe those are the leaf certificates issued to end users of Let's Encrypt. The root certificates of Let's Encrypt are valid for a much longer amount of time. Since `cbl` 2.1.0 [`pinnedServerCertificate`](https://pub.dev/documentation/cbl/latest/cbl/ReplicatorConfiguration/pinnedServerCertificate.html) supports not just leaf certificates but also intermediate and root certificates.

**Comment by filipenanclarez** [comment]
> > Your version of cbl 2.1.0 update dependences (specially ffi) and force the anroid minimum sdk to 33. This put all my clients with android 6 out of game.
> 
> I was not aware of those changes to the minimum SDK in dependencies. Couchbase Lite itself has a minimum of 22 and that is what I try to support, too. I'll look into lowering the dependency constraints where possible, but it would be helpful if you could point out the specific dependencies that require these minimum SDK versions.
> 
> > About your workaround, the problem is the let's encrypt renew certificates after 3 months. So every time the certificates renews, i need build another version of app.
> 
> I believe those are the leaf certificates issued to end users of Let's Encrypt. The root certificates of Let's Encrypt are valid for a much longer amount of time. Since `cbl` 2.1.0 [`pinnedServerCertificate`](https://pub.dev/documentation/cbl/latest/cbl/ReplicatorConfiguration/pinnedServerCertificate.html) supports not just leaf certificates but also intermediate and root certificates.

As i said,  the dependece is FFI. I know the other package mentioned is not you responsability, but because you update of FFI, then this force update various packages in cascade. If i update fille_picker, then update another, and another, and lastly, Android6 is not supported anymore.

Can you keep the previous version of FFI ?

```
Because cbl >=2.1.0 depends on ffi ^2.0.1 and file_picker 4.6.1 depends on ffi ^1.1.2, cbl >=2.1.0 is incompatible with file_picker 4.6.1.
So, because memodu depends on both file_picker 4.6.1 and cbl 2.1.0, version solving failed.
```

**Comment by filipenanclarez** [comment]
> > Your version of cbl 2.1.0 update dependences (specially ffi) and force the anroid minimum sdk to 33. This put all my clients with android 6 out of game.
> 
> I was not aware of those changes to the minimum SDK in dependencies. Couchbase Lite itself has a minimum of 22 and that is what I try to support, too. I'll look into lowering the dependency constraints where possible, but it would be helpful if you could point out the specific dependencies that require these minimum SDK versions.
> 
> > About your workaround, the problem is the let's encrypt renew certificates after 3 months. So every time the certificates renews, i need build another version of app.
> 
> I believe those are the leaf certificates issued to end users of Let's Encrypt. The root certificates of Let's Encrypt are valid for a much longer amount of time. Since `cbl` 2.1.0 [`pinnedServerCertificate`](https://pub.dev/documentation/cbl/latest/cbl/ReplicatorConfiguration/pinnedServerCertificate.html) supports not just leaf certificates but also intermediate and root certificates.

Ok, my fault. Now i'm here on cbl 2.1.0. I remove the pinnedCertificate param, and ...

... now i got this error:

```
I/flutter ( 9941): 15:12:29.157395| [DB] error: mbedTLS(C): x509_verify_cert() returned -9984 (-0x2700)
I/flutter ( 9941): 15:12:29.165543| [DB] error: mbedTLS(C): SockPP: mbedtls error -0x2700 from mbedtls_ssl_handshake: X509 - Certificate verification failed, e.g. CRL, CA or signature check failed
I/flutter ( 9941): 15:12:29.226430| [DB] error: mbedTLS(C): SockPP: ---closing mbedtls_socket with error (mbed status -0x2700, last_error -9984) ---
I/flutter ( 9941): 15:12:29.230412| [WS] error: TCPSocket TLS handshake failed; cert verify status 0x01
I/flutter ( 9941): 15:12:29.233735| [WS] error: {N8litecore9websocket16BuiltInWebSocketE#2} WebSocket failed to connect! (reason=Network error 7)
I/flutter ( 9941): 15:12:29.236445| [Sync] error: {Repl#1} Got LiteCore error: Network error 7, "The certificate validity has expired"
```

Access url with browser show me valid TLS/Certificate status.

I still need to add a pinned certificate for Let'Encrypt?

**Comment by blaugold** [comment]
Regarding the dependencies: I do need version >2.0.0 of `ffi`, but looking at the [android part](https://github.com/miguelpruivo/flutter_file_picker/blob/master/android/build.gradle#L25-L28) of `file_picker` you should be able to support Android SDK 16, since that's the `minSdkVersion`. Only the `compileSdkVersion` is 33.

---

Sorry, I probably was not clear enough about the Let's Encrypt certificate. You still need to provide a certificate in [`pinnedServerCertificate`](https://pub.dev/documentation/cbl/latest/cbl/ReplicatorConfiguration/pinnedServerCertificate.html), but it can now be the root certificate of Let's Encrypt, which is valid for much longer than 3 months.

You most likely need to use the ISRG Root X1 [Let's Encrypt certificate](https://letsencrypt.org/certificates/).

**Comment by filipenanclarez** [comment]
> Sorry, I probably was not clear enough about the Let's Encrypt certificate. You still need to provide a certificate in [`pinnedServerCertificate`](https://pub.dev/documentation/cbl/latest/cbl/ReplicatorConfiguration/pinnedServerCertificate.html), but it can now be the root certificate of Let's Encrypt, which is valid for much longer than 3 months.
> 
> You most likely need to use the ISRG Root X1 [Let's Encrypt certificate](https://letsencrypt.org/certificates/).

I try to use the root ISRG Root X1, but still got this error on Android 6 device and CBL 2.1.0

![image](https://user-images.githubusercontent.com/27212546/193923171-7dc3e2b5-b8b6-4d17-865c-5c7b5bd5f196.png)

**Comment by blaugold** [comment]
Hmm. What is your setup to make the server available through TLS? Are you using a proxy? 

The server needs to serve the complete certificate chain. If you are using certbot that should already be the case.

In any case, you could try setting the ISRG Root X1 certificate as the only trusted root certificate through [`trustedRootCertificates`](https://pub.dev/documentation/cbl/latest/cbl/ReplicatorConfiguration/trustedRootCertificates.html) instead of using `pinnedServerCertificate`.

**Comment by blaugold** [comment]
If your server is publicly available, it would be helpful if you could share its hostname with me. That would allow me to take a look at the configured certificate chain.

**Comment by filipenanclarez** [comment]
> Hmm. What is your setup to make the server available through TLS? Are you using a proxy?
> 
> The server needs to serve the complete certificate chain. If you are using certbot that should already be the case.
 
This is my setup: 

https://dev.to/filipenanclarez/protegendo-a-comunicacao-do-flutter-com-o-couchbase-19jo#chapter-3

> In any case, you could try setting the ISRG Root X1 certificate as the only trusted root certificate through [`trustedRootCertificates`](https://pub.dev/documentation/cbl/latest/cbl/ReplicatorConfiguration/trustedRootCertificates.html) instead of using `pinnedServerCertificate`.

Ok, i will try e back here...

**Comment by filipenanclarez** [comment]
> If your server is publicly available, it would be helpful if you could share its hostname with me. That would allow me to take a look at the configured certificate chain.

Yes, of course. But not entire server is over TLS, only sync_gateway, so you can check on this endpoing:

https://memotai.com:4984/

Also, a relevant point: This error do not occur in another devices, even with or without `pinnedServerCertificate`. Only on this specific device with Android 6.0.1 (Samsung Tab SM700) we have this problem.

**Comment by blaugold** [comment]
That's great! Thanks for letting me know.
