### ISSUE TITLE
Replicator: trustedRootCertificates missing

### ISSUE THREAD

**Issue by florianfiby** [cbl-dart/cbl-dart#410]
**Describe the bug**

I am unable to connect on a wss Endpoint on IOS even the SSL chain is valid on safari and every other client.
The workaround is to use trustedRootCertificates, but even it's supported on couchbase-lite-C, it is missing in cbl-dart.

**To Reproduce**

1. start replicator an wss endpoint

**Expected behavior**

set trusted root certificate manually

**Screenshots**

-

**Environment (please complete the following information):**

 - OS:
 - `cbl`:
 - `cbl_flutter`:
 - `cbl_flutter_ce`:

**Additional context**

-

**Comment by florianfiby** [comment]
#411

**Comment by florianfiby** [comment]
@blaugold do you have plans for the next release and publishing on https://pub.dev/packages/cbl?

**Comment by blaugold** [comment]
@florianfiby I just published a new release.
