### ISSUE TITLE
Compatibility problem with inappwebview package in Android 5.1 - Failed to load dynamic library 'libcblite.so': dlopen failed: library "libcblite.so" not found

### ISSUE THREAD

**Issue by filipenanclarez** [cbl-dart/cbl-dart#425]
**Describe the bug**

When add inappwebview package, the app cannot load couchbase library on Android 6.0.1 or earlier.

Both in emulators and in physical devices (tested with API22 Android emulator and Samsung SM700 physical device)

**To Reproduce**

- Create a emulator with Nexus 5 Android 5.1 API22 and X86 platform
- Create a empty project 
- Add cbl, cbl_flutter, cbl_flutter_ce and flutter_inappwebview
- Make changes in build.gradle to minsdk=22 and compilesdk=33
- Change main function to this:

```dart
import 'package:flutter/material.dart';
import 'package:cbl_flutter/cbl_flutter.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await CouchbaseLiteFlutter.init();
  runApp(const MyApp());
}
```
- Run the app

Please look the reproducible example on this public repository : https://github.com/filipenanclarez/couchlite_issue_425

**Expected behavior**

The library correctly load.

**Screenshots**

![image](https://user-images.githubusercontent.com/27212546/194346196-805b6fd4-81c7-43d6-a797-7f8dd6772c11.png)

**Environment (please complete the following information):**

 - OS: Android 6.0.1 or earlier
 - `cbl`: 2.1.0
 - `cbl_flutter`: 2.0.1
 - `cbl_flutter_ce`: 2.1.1
 - `flutter_inappwebview`: ^5.4.4+3

**Additional context**

```
I/flutter ( 4746): Invalid argument(s): Failed to load dynamic library 'libcblite.so': dlopen failed: library "libcblite.so" not found
I/flutter ( 4746):
I/flutter ( 4746): #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:12:43)
I/flutter ( 4746): #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:23:12)
I/flutter ( 4746): #2      _extension#0._createDynamicLibrary
package:cbl_ffi/src/libraries.dart:96
I/flutter ( 4746): #3      new DynamicLibraries.fromConfig.<anonymous closure>
package:cbl_ffi/src/libraries.dart:45
I/flutter ( 4746): #4      new DynamicLibraries._loadLibraries
package:cbl_ffi/src/libraries.dart:59
I/flutter ( 4746): #5      new DynamicLibraries.fromConfig
package:cbl_ffi/src/libraries.dart:43
I/flutter ( 4746): #6      new CBLBindings
package:cbl_ffi/src/bindings.dart:31
I/flutter ( 4746): #7      CBLBindings.init
package:cbl_ffi/src/bindings.dart:64
I/flutter ( 4746): #8      _initIsolate
package:cbl/…/support/isolate.dart:68
I/flutter ( 4746): #9      initPrimaryIsolate
package:cbl/…/support/isolate.dart:53
I/flutter ( 4746): #10     CouchbaseLiteFlutter.init.<anonymous closure>
package:cbl_flutter/cbl_flutter.dart:20
I/flutter ( 4746): <asynchronous suspension>
I/flutter ( 4746): #11     main.<anonymous closure>
package:memodu/main.dart:79
I/flutter ( 4746): <asynchronous suspension>
I/flutter ( 4746): ----------------------------------------------------
I/TRuntime.CctTransportBa( 4746): Making request to: https://crashlyticsreports-pa.googleapis.com/v1/firelog/legacy/batchlog
I/TRuntime.CctTransportBa( 4746): Status Code: 200
```

**Comment by filipenanclarez** [comment]
@blaugold please help... this issue stuck my whole project here...

**Comment by blaugold** [comment]
I can replicate the issue, but since `flutter_inappwebview` apparently prevents the loading of shared libraries on older versions of Android, I don't think there is anything I can do.

**Comment by filipenanclarez** [comment]
> I can replicate the issue, but since `flutter_inappwebview` apparently prevents the loading of shared libraries on older versions of Android, I don't think there is anything I can do.

Can you check if using this workaround can help?

https://github.com/flutter/flutter/issues/59834#issuecomment-1223471763

Aparently using System.loadLibrary on java side before call DynamicLivraby open, can bypass the problem.

**Comment by blaugold** [comment]
I cannot do the `System.loadLibrary` calls in the Flutter plugin because I cannot control the order in which plugins are registered. But you can in your app:

```kotlin
package com.example.couchlite_issue_425

import android.os.Bundle
import io.flutter.embedding.android.FlutterActivity

class MainActivity: FlutterActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        System.loadLibrary("cblite");
        System.loadLibrary("cblitedart");
        super.onCreate(savedInstanceState)
    }
}

```

**Comment by filipenanclarez** [comment]
> I cannot do the `System.loadLibrary` calls in the Flutter plugin because I cannot control the order in which plugins are registered. But you can in your app:
> 
> ```kotlin
> package com.example.couchlite_issue_425
> 
> import android.os.Bundle
> import io.flutter.embedding.android.FlutterActivity
> 
> class MainActivity: FlutterActivity() {
>     override fun onCreate(savedInstanceState: Bundle?) {
>         System.loadLibrary("cblite");
>         System.loadLibrary("cblitedart");
>         super.onCreate(savedInstanceState)
>     }
> }
> ```

YEAHP !!!! Amazing !!!

Thank you a lot.
