### ISSUE TITLE
Query execute or explain stops/breaks main thread without execption or killing the app

### ISSUE THREAD

**Issue by nblum37** [cbl-dart/cbl-dart#453]
Hi :)

**Describe the bug**

We face a very strange issue that exists since we updated some code generation packages for serialization. The environment consists of two databases, one database is synced to the backend (DBsync) and the second one is only used as local storage (DBlocal). I can query a specific query A on DBlocal without any problems. However, executing a specific query B on DBsync first and then the query A on DBlocal leads to a strange stop/break of the main thread, causing the app to stop (except for one background isolate of a location package). We do not see any error logs in the console (cbl logging level verbose) and even hot restart does not work anymore. However some how, the app itself is not really killed but is still alive. So when I pause and resume the app, I get some logs in the console about pausing and resuming the app.
If I jump into the query execute() function, I can see that final `resultSetId = await channel!.call(ExecuteQuery(queryId: objectId!));` (line 61 at `procy_query.dart`) gets called, but the next line return `ProxyResultSet(...` will never be reached.
My question is: Do you have any suggestions on how I can get more information on where and why the database query crashes the whole app?
The really strange thing is, that the queries are working fine before changing the packages of the code generator and fixing the breaking changes. I have no clue how these two things can be connected.

**To Reproduce**

Currently not possible to provide. It seems to be some kind of system issue.

**Environment:**

 - OS: Android
 - `cbl`: 2.1.3
 - `cbl_flutter`: 2.0.2
 - `cbl_flutter_ce`: 2.1.2

**Comment by blaugold** [comment]
Could you set up file logging and share the log files after triggering the issue?

```dart
// Example log files setup.

final documentsDirectory = await getApplicationDocumentsDirectory();
final logsDirectory = path.join(documentsDirectory.path, 'CouchbaseLiteLogs');
Database.log.file
  ..config = LogFileConfiguration(
    directory: logsDirectory,
    usePlainText: true,
  )
  ..level = LogLevel.verbose;
```

**Comment by nblum37** [comment]
Thanks for your fast reply! I just wanted to close this issue already. It seems like, that it is more an issue with the debugger, that led to the query execution as the source of the error. Classical print statement debugging now leads to another error source.

**Comment by blaugold** [comment]
👍  Ah, thanks for letting me know.
