### ISSUE TITLE
Feature Request: Access "_attachments" meta field

### ISSUE THREAD

**Issue by nblum37** [cbl-dart/cbl-dart#456]
Hi,

every `Document` class offers access to certain meta properties like `id` (`_id`) or `rev` (`_rev`). In addition, the Sync Gateway is also providing (sometimes) the meta key `_attachments`. It would be nice to add this property to the `Document` class, as well, if possible. It would help to get a fast overview, of where attachments are located within the document.

Not sure, if it is clear, what I mean?

Thank you :)

**Comment by blaugold** [comment]
I think I know what you mean. I'm trying to keep the Dart API as consistent as possible with the APIs of the official SDKs, which is why I'm a bit reluctant to add this field.

**Comment by biozal** [comment]
I DO NOT recommend this.  Those fields can change at anytime and aren't "officially" supported in the sense that they have and will change without notice.

**Comment by nblum37** [comment]
Ok, thank you for the feedback. Makes complete sense and I will close this issue

**Comment by nblum37** [comment]
Maybe out of interest: Is there any other possibility to get all linked blobs to a document at CBL?

**Comment by biozal** [comment]
In my humble opinion, it depends on how much work you want to do on your end.  

So you could add in an field to your document anytime you attach something to a document, a bool called `hasAttachment` or something like that that sets to true if there is an attachment.  Now I know you are going to say what if the attachment was attached from outside of the mobile apps, and yes that is a possibility.  However, you could add some business logic into your sync function in Sync Gateway/App Services that checks the meta data to see if attachment is there and if so set your tracking bool field (in my example `hasAttachment`) to true.  If Couchbase changes it's meta data backend, then you would only need to update your sync function.  This would require you to read updates notes on sync gateway/app services to understand when things change what you need to do, but it does abstract out how you check to make it easier on you.  

If I was personally working on a project I would probably do this.  The advantage of having a field you control means you can put an index on that field making finding documents with an attachment a lot faster on slower devices and doesn't introduce table scanning.

**Comment by nblum37** [comment]
Thanks for that input!

**Comment by biozal** [comment]
Anytime - I love this community and we all are just to trying to help each other make great apps!

**Comment by biozal** [comment]
FYI many other ways to do this BTW.  If you are saving an attachment on a user profile document, maybe using the key `avatar`, you can also use the IFMISSINGRONULL or IFMISSING functions in SQL++ (https://cbl-dart.dev/queries/sqlplusplus-mobile/#conditional-functions) to find documents with the key avatar missing.  Again it will be depend on why you are trying to find documents with or without attachments.  I think some developers forget SQL++ supports some really cool things that regular SQL doesn't support.

**Comment by nblum37** [comment]
We have the issue, that documents can get very complex (up to 3KB für JSON text) and attachments are allowed to exist nearly everywhere in this structure. The question was, how do I know where to look for the attachments without going through the whole data structure recursively and checking for blob objects? Unfortunately, we can not really influence the document during the creation process. So relying on additional keys could be hard, but it might be possible.
