### ISSUE TITLE
Flutter 3.7 causes fatal crash on iOS

### ISSUE THREAD

**Issue by nblum37** [cbl-dart/cbl-dart#459]
Hi :)

**Describe the bug**

The (nearly) same code runs fine under Android for Flutter 3.3.10 and Flutter 3.7.3 However, it can only be run under Flutter 3.3.10 if applied to iOS. At iOS we observe a fatal crash shortly after the database and its replicator were initialized (under 3.7.3).

**Log Data**
Sentry stack trace:
[b3e9976dfd2e4d45a4bd052e5fbd0e2a-symbolicated.log](https://github.com/cbl-dart/cbl-dart/files/10762429/b3e9976dfd2e4d45a4bd052e5fbd0e2a-symbolicated.log)

**Environment (please complete the following information):**

 - OS: iOS
 - Flutter: 3.7.3
 - `cbl`: 2.1.4
 - `cbl_flutter`: 2.0.2
 - `cbl_flutter_ce`: 2.1.2

**Comment by blaugold** [comment]
Thanks for the stack trace. 

I tried updating the CI to the current stable Flutter channel and saw crashes, but haven't had the time yet to look into it. Hopefully, I get to it this weekend.

**Comment by blaugold** [comment]
The fix for this issue is in the latest release.
