### ISSUE TITLE
openasync will sliently crash in isolate

### ISSUE THREAD

**Issue by function1983** [cbl-dart/cbl-dart#460]
**Describe the bug**

I have an app that use cbl. When the db get to a certain size, if I open a database instance with openasync, and immediately make a write request, the app will silently stop working. After the failed write request, no sub-sequential data communications to cbl isolate is possible since I believe an exception was thrown but no errors or warnings in the main thread.

**To Reproduce**

`Steps to reproduce the behavior:`
1. db = await Database.openAsync("dbName", conf);
2. db.saveDocument(...);
3. will cause silent isolate exception

`This works:`
db = Database.openSync("dbName", conf);
db.saveDocument(...)

`This works:`
db = await Database.openAsync("dbName", conf);
await Future.delayed(Duration(milliseconds: 100));
db.saveDocument(...)

`This DOES NOT work:`
db = await Database.openAsync("dbName", conf);
await Future.delayed(Duration(milliseconds: 10)); //change 100 to 10
db.saveDocument(...)

**Expected behavior**

Errors bubbling up in logs.

**Environment (please complete the following information):**

cbl: ^2.1.4
cbl_flutter: ^2.0.2
cbl_flutter_ce: ^2.1.2
[✓] Flutter (Channel stable, 3.7.3, on Pop!_OS 22.04 LTS 5.19.0-76051900-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.73.1)
[✓] Connected device (3 available)

**Additional context**

I was so confused since the app has been working quite stable for 2 years+. The write request was there for a long time. But now problems starts popping up with long time users intermittently. I narrowed down the problem to this bug.  What frustrated me that there is no error even with a try catch. Maybe I am not an expert with dart isolate error catching.

**Comment by blaugold** [comment]
Is it possible that this issue started after upgrading Flutter to 3.7.0? I know that there are other problems with 3.7.0 (https://github.com/cbl-dart/cbl-dart/issues/459) that I'm currently looking into.

**Comment by blaugold** [comment]
I've just published new releases of the packages, that contain a fix for #459. Please try upgrading and let me know if that fixes this issue.

**Comment by function1983** [comment]
Thank you. The update handles exceptions in isolate gracefully instead of crashing.
