### ISSUE TITLE
How to connect Cloud couch base

### ISSUE THREAD

**Issue by AnandSaran** [cbl-dart/cbl-dart#494]
Hi in the code i can see only local DB.
There is no code to connect Cloud CouchBase DB.
can you help me how to connect  Cloud CouchBase DB.?
Thanks

**Comment by biozal** [comment]
This SDK is for Couchbase Lite, not Couchbase Capella.  You can use this with Couchbase Capella App Services if you like, but if you are trying to talk to Couchbase Capella directly, there is no SDK for Dart to do this.

**Comment by blaugold** [comment]
Actually, I got started on a Dart SDK for Couchbase Server ([`package:couchbase`](https://pub.dev/packages/couchbase)). 🤓 But it's not quite ready yet for production.

I'm going to close this issue since it's not directly related to Couchbase Lite.
