### ISSUE TITLE
ReplicatorConfiguration() missing CollectionConfiguration() parameter in cbl: ^3.0.0-dev.1"

### ISSUE THREAD

**Issue by Konst80** [cbl-dart/cbl-dart#535]
**Describe the bug**

In version cbl: ^3.0.0-dev.1, the `ReplicatorConfiguration()` does not include a parameter for `CollectionConfiguration()` which should be used, instead of the `database` parameter.

The following code results in the message mentioned below:

Code:
```
 final replicatorConfiguration = ReplicatorConfiguration(
        database: database,
        enableAutoPurge: true,
        continuous: true,
        replicatorType: ReplicatorType.pushAndPull,
        authenticator: SessionAuthenticator(sessionId: sessionID),
        target: UrlEndpoint(Uri.parse(CouchbaseConfig.syncUrl)));
```
Message:
```
'database' is deprecated and shouldn't be used. Add a CollectionConfiguration for the default collection instead.
Try replacing the use of the deprecated member with the replacement.dart[deprecated_member_use](https://dart.dev/diagnostics/deprecated_member_use)
```

Consequently, the corrected code should look like this:

```
    final collectionConfiguration = CollectionConfiguration(channels: channels);

    final replicatorConfiguration = ReplicatorConfiguration(
        collectionConfiguration: CollectionConfiguration,
        enableAutoPurge: true,
        continuous: true,
        replicatorType: ReplicatorType.pushAndPull,
        authenticator: SessionAuthenticator(sessionId: sessionID),
        target: UrlEndpoint(Uri.parse(CouchbaseConfig.syncUrl)));
```
However, the issue is that there isn't a parameter available to pass over the `CollectionConfiguration` instance. The code above cannot be compiled as is.

**Expected behavior**

The function should have a required parameter to pass over the `CollectionConfiguration` instance.

**Environment (please complete the following information):**

This issue occurs in any environment, as it's not related to code compilation.

**Comment by blaugold** [comment]
Closing this issue, since I've answered the question in https://github.com/cbl-dart/cbl-dart/discussions/534.
