### ISSUE TITLE
Documents with subdocuments greater than 48 fail to sync with error "[DB] error: Fleece encoder convertJSON failed (5)"

### ISSUE THREAD

**Issue by admosity** [cbl-dart/cbl-dart#539]
**Describe the bug**

Documents with more than 48 subdocuments appear to fail to sync due to a fleece encoding error. An upstream issue was logged here in the fleece encoder with reproduction: https://github.com/couchbase/fleece/issues/192

**To Reproduce**

1. Add a document with more than 48 subdocuments
2. Observe an error that looks like this:
    ```
    flutter: 18:14:03.972149| [DB] error: Fleece encoder convertJSON failed (5)
    flutter: 18:14:03.972656| [Sync] warning: {IncomingRev#4} failed with error: Fleece error 5, "Incoming rev failed to encode"
    ```

**Expected behavior**

Should be able to sync documents with >48 nested documents.

**Screenshots**

![image](https://github.com/cbl-dart/cbl-dart/assets/4655972/78f0ed34-c759-4f74-aaa9-3eacb558bfe3)

**Environment (please complete the following information):**

 OS: iOS 17.0

 ```yaml
  cbl: ^2.2.2
  cbl_flutter: ^2.0.9
  cbl_flutter_ee: ^2.2.2
 ```

**Additional context**

The error appears to be coming from here https://github.com/couchbase/couchbase-lite-core/blob/c71b492329bbeade1e0be8c61eed16fdd1055b43/Replicator/IncomingRev.cc#L151-L156

**Sample documents**
WORKS: [48.json](https://github.com/cbl-dart/cbl-dart/files/13246277/48.json)
DOESN'T WORK: [49.json](https://github.com/cbl-dart/cbl-dart/files/13246278/49.json)

**Comment by blaugold** [comment]
Thanks for reporting this issue!

The JSON decoder used by Fleece is currently configured to a maximum of 50 levels of nesting:

https://github.com/blaugold/fleece/blob/7268d2c2b3c0334c87e6ae5a99cc26b4baf7e33f/Fleece/Core/JSONConverter.cc#L35

This JSON decoder is used during replication at the location you pointed out as the origin of the error.

If you are a Couchbase customer, please contact Couchbase support to expediate resolving this issue.

**Comment by admosity** [comment]
Thanks for digging in! Can confirm that recompiling fleece after changing that value that it does work:

```
./fleeceTool --encode 49.json | hexdump -C                                                               
00000000  70 01 41 61 00 01 70 01  41 61 80 05 70 01 41 61  |p.Aa..p.Aa..p.Aa|
00000010  80 05 70 01 41 61 80 05  70 01 41 61 80 05 70 01  |..p.Aa..p.Aa..p.|
00000020  41 61 80 05 70 01 41 61  80 05 70 01 41 61 80 05  |Aa..p.Aa..p.Aa..|
00000030  70 01 41 61 80 05 70 01  41 61 80 05 70 01 41 61  |p.Aa..p.Aa..p.Aa|
00000040  80 05 70 01 41 61 80 05  70 01 41 61 80 05 70 01  |..p.Aa..p.Aa..p.|
00000050  41 61 80 05 70 01 41 61  80 05 70 01 41 61 80 05  |Aa..p.Aa..p.Aa..|
00000060  70 01 41 61 80 05 70 01  41 61 80 05 70 01 41 61  |p.Aa..p.Aa..p.Aa|
00000070  80 05 70 01 41 61 80 05  70 01 41 61 80 05 70 01  |..p.Aa..p.Aa..p.|
00000080  41 61 80 05 70 01 41 61  80 05 70 01 41 61 80 05  |Aa..p.Aa..p.Aa..|
00000090  70 01 41 61 80 05 70 01  41 61 80 05 70 01 41 61  |p.Aa..p.Aa..p.Aa|
000000a0  80 05 70 01 41 61 80 05  70 01 41 61 80 05 70 01  |..p.Aa..p.Aa..p.|
000000b0  41 61 80 05 70 01 41 61  80 05 70 01 41 61 80 05  |Aa..p.Aa..p.Aa..|
000000c0  70 01 41 61 80 05 70 01  41 61 80 05 70 01 41 61  |p.Aa..p.Aa..p.Aa|
000000d0  80 05 70 01 41 61 80 05  70 01 41 61 80 05 70 01  |..p.Aa..p.Aa..p.|
000000e0  41 61 80 05 70 01 41 61  80 05 70 01 41 61 80 05  |Aa..p.Aa..p.Aa..|
000000f0  70 01 41 61 80 05 70 01  41 61 80 05 70 01 41 61  |p.Aa..p.Aa..p.Aa|
00000100  80 05 70 01 41 61 80 05  70 01 41 61 80 05 70 01  |..p.Aa..p.Aa..p.|
00000110  41 61 80 05 70 01 41 61  80 05 70 01 41 61 80 05  |Aa..p.Aa..p.Aa..|
00000120  70 01 41 61 80 05 80 03                           |p.Aa....|
00000128
```

**Comment by blaugold** [comment]
In CBL C SDK 3.1.6 the limit has been expanded to a max nesting of 100 levels. https://github.com/cbl-dart/cbl-dart/pull/577
