### ISSUE TITLE
Support vector search

### ISSUE THREAD

**Issue by brian-at-pieces** [cbl-dart/cbl-dart#621]
**Describe the bug**

Hey there! I noticed that you just bumped libcblite to 3.2.0 - do you have any plans to support the [vector search feature](https://docs.couchbase.com/couchbase-lite/current/cbl-whatsnew.html?_gl=1*j2zp7r*_gcl_aw*R0NMLjE3MjgzMTYzMDQuQ2owS0NRandqWTY0QmhDYUFSSXNBSWZjN1laU29nY0VqcFozNDRaOHQxeHJEbnZwVE52MW1ac1N6VW5pZEJ6T19qN28tYi1PWDZnaGJXOGFBcHFURUFMd193Y0I.*_gcl_au*MjA5NjExNjE1NS4xNzI4MDQ3NzMz) that was released in this version? We'd love to implement this in our app! Thanks.

**Comment by brian-pieces** [comment]
Small world - thanks for the interest! 

Bummer about the native assets progress, but glad to hear the vector search is in the works!

**Comment by brian-at-pieces** [comment]
Hey @blaugold, just wanted to check in here and see if there's been any progress? Thanks!

**Comment by blaugold** [comment]
- [ ] [IndexUpdater](https://docs.couchbase.com/mobile/3.2.1/couchbase-lite-swift/Classes/IndexUpdater.html#/s:18CouchbaseLiteSwift12IndexUpdaterC10skipVector2atySi_tF)
- [ ] [VectorIndexConfiguration](https://docs.couchbase.com/mobile/3.2.1/couchbase-lite-swift/Structs/VectorIndexConfiguration.html#/s:18CouchbaseLiteSwift24VectorIndexConfigurationV10dimensionss6UInt32Vvp)
- [ ] [Prediction](https://docs.couchbase.com/mobile/3.2.1/couchbase-lite-swift/Classes/Prediction.html#/s:18CouchbaseLiteSwift10PredictionC13registerModel_8withNameyAA010PredictiveF0_p_SStF)
  - [PredictiveModel](https://docs.couchbase.com/mobile/3.2.1/couchbase-lite-swift/Protocols/PredictiveModel.html#/s:18CouchbaseLiteSwift15PredictiveModelP7predict5inputAA16DictionaryObjectCSgAG_tF)

**Comment by blaugold** [comment]
🎉 Vector search is now available in the latest dev releases:

[cbl - v3.3.0-dev.4](https://github.com/cbl-dart/cbl-dart/blob/main/CHANGELOG.md#cbl---v330-dev4)
[cbl_flutter - v3.2.0-dev.5](https://github.com/cbl-dart/cbl-dart/blob/main/CHANGELOG.md#cbl_flutter---v320-dev5)
[cbl_dart - v3.2.0-dev.4](https://github.com/cbl-dart/cbl-dart/blob/main/CHANGELOG.md#cbl_dart---v320-dev4)
[cbl_generator - v0.3.1-dev.4](https://github.com/cbl-dart/cbl-dart/blob/main/CHANGELOG.md#cbl_generator---v031-dev4)
[cbl_sentry - v2.1.2-dev.4](https://github.com/cbl-dart/cbl-dart/blob/main/CHANGELOG.md#cbl_sentry---v212-dev4)
[cbl_flutter_ce - v3.3.0-dev.7](https://github.com/cbl-dart/cbl-dart/blob/main/CHANGELOG.md#cbl_flutter_ce---v330-dev7)
[cbl_flutter_ee - v3.3.0-dev.7](https://github.com/cbl-dart/cbl-dart/blob/main/CHANGELOG.md#cbl_flutter_ee---v330-dev7)

**Comment by brian-at-pieces** [comment]
Awesome, thanks for this! Will test out shortly.

**Comment by blaugold** [comment]
Vector search is now also available in the latest stable release.
