### ISSUE TITLE
Data created inside collection are not synced to capella couchbase 

### ISSUE THREAD

**Issue by richard457** [cbl-dart/cbl-dart#627]
```dart
  final collection = await capella?.flipperDatabase
          ?.createCollection("collection", "config");

      await capella!.flipperDatabase!.writeN(
          tableName: "your_table_name",
          writeCallback: () {
            Map<String, dynamic> map = {"id": 15002};
            // final db = ProxyService.capela.capella!.db!;

            // Create a document with the given ID and map data
            final document = MutableDocument.withId("15002", map);

            // Return the created document (of type T, in this case a MutableDocument)
            return document;
          },
          onAdd: (doc) async {
            // After the write operation, save the document to the collection

            await collection!.saveDocument(doc);

            // Optionally, you can log or perform further operations here
            talker.warning("Document saved: ${doc.id}");
          });
```
If I use defaultCollection I can see data with ID 15002 to https://cloud.couchbase.com/ synced successfully I am doing something wrong?

**Comment by richard457** [comment]
so it seems   flipperDatabase
         ?.createCollection("counters", "config") is not creating same scope and collection to cloud.couchbase.com

**Comment by biozal** [comment]
So a few things:
No mobile version of Couchbase Lite creates collections automatically to Couchbase Capella.  The workflow should be:

- Create Scopes and Collections in Couchbase Capella
- In Couchbase Capella, Create App Service Endpoint linking the scope and collections you want to sync.  Setup Sync script and assign documents to channels based on your users.
- In your mobile app you would then make sure you create the same scope and collections you want to sync.
- In your replicator configuration you would need to send in an array of those collections along with a blank CollectionConfig unless you want to filter documents further, at which you would add your channel and document filters to the Replicators Collection Config.
- Start replication.

To troubleshoot, you could listen to the Replicator Status or turn on logging and read the logs to see what documents are getting synced.

**Comment by richard457** [comment]
Thanks for the clarification, my thinking was otherway around, let me try to first create collection and scope on Capella side and see thank you very much.

**Comment by richard457** [comment]
My findings
Creating same scope and collections  at https://cloud.couchbase.com and create same on local 
![image](https://github.com/user-attachments/assets/31d02ce3-4157-49b3-99f5-72c222b519df)
```dart
 final collection = await capella!.flipperDatabase!
          .createCollection(countersTable, scope);
      // talker.warning(scope);
      // talker.warning(countersTable);

      await capella!.flipperDatabase!.writeN(
          tableName: countersTable,
          writeCallback: () {
            Counter counter = Counter(id: randomNumber(), curRcptNo: 1111);

            // final db = ProxyService.capela.capella!.flipperDatabase!;

            // Create a document with the given ID and map data
            final document =
                MutableDocument.withId(counter.id.toString(), counter.toJson());

            // Return the created document (of type T, in this case a MutableDocument)
            return document;
          },
          onAdd: (doc) async {
            // After the write operation, save the document to the collection

            await collection.saveDocument(doc);

            // Optionally, you can log or perform further operations here
            talker.warning("Document saved: ${doc.id}");
          });

      // print(collection);
      final query = const QueryBuilder()
          .select(SelectResult.all())
          .from(DataSource.collection(collection))
          .where(Expression.property('curRcptNo')
              .equalTo(Expression.integer(1111)))
          .limit(Expression.integer(1));

      final result = await query.execute();
      final results = await result.allResults();
```
I realized when saving data in scope other than _default otherwise data will not be synced to the capella, also  the query
```dart
 final query = const QueryBuilder()
          .select(SelectResult.all())
          .from(DataSource.collection(collection))
          .where(Expression.property('curRcptNo')
              .equalTo(Expression.integer(1111)))
          .limit(Expression.integer(1));
```
will return nothing when scope and collection used are not _default.

**Comment by richard457** [comment]
![image](https://github.com/user-attachments/assets/586cb80d-2629-4f97-aa53-90ac6c00514c)
 cc @biozal

**Comment by richard457** [comment]
However, I think the part
# In your replicator configuration you would need to send in an array of those collections along with a blank CollectionConfig I might be doing something wrong maybe example could help

**Comment by richard457** [comment]
I managed to get data to sync to the capella but the issue I think is when using collection and scope other than _default
this query 
```dart
   final query = const QueryBuilder()
          .select(SelectResult.all())
          .from(DataSource.collection(collection))
          .where(Expression.property('curRcptNo')
              .equalTo(Expression.integer(1111)))
          .limit(Expression.integer(1));
```
always return null

**Comment by richard457** [comment]
I did find solution Thank you very much, I think documentation can be improved to show how to set up capella and sync.
